name: Generate Data

on:
  schedule:
    - cron: '0 */12 * * *'  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master  # Consider pinning to a specific version
        with:
          github_user_name: shirleyfyx
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
